[package]
name = "texcraft-bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "texcraft"
path = "src/texcraft.rs"

[[bin]]
name = "randtex"
path = "src/randtex.rs"

[dependencies]
clap = {version="4.3.3", default-features=false, features=["std", "derive"]}
colored = "2"
rand = "0.8.4"
rmp-serde = {version="^1.0"}
serde_json = {version="1.0"} 

texlang = { path = "../crates/texlang" }
texlang-stdlib = { path = "../crates/texlang-stdlib", features = ["repl", "serde"]}
performance = {path = "../performance"}
