[package]
name = "texcraft"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "texcraft"
path = "src/texcraft.rs"

[[bin]]
name = "randtex"
path = "src/randtex.rs"

[dependencies]
clap = {version="3.0.0-beta.5", default-features=false, features=["std", "derive"]}
anyhow = "1.0"
colored = "2"
rand = "0.8.4"

texlang-core = { path = "../crates/texlang-core" }
texlang-stdlib = { path = "../crates/texlang-stdlib", features = ["repl"]}
performance = {path = "../performance"}
