[package]
name = "texcraft-stdext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Used for diffing strings in the spell check module.
colored = "2"
