[package]
name = "tfm-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version="4.4.8", features=["derive"]}
tfm = { version = "0.1", path = "../", features = ["ariadne"]}
ariadne = {version="0.3.0"}

[[bin]]
name = "tfmtools"
path = "src/tfmtools.rs"
