[package]
name = "tfm-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version="4.4.8", features=["derive", "wrap_help"]}
tfm = { version = "0.1", path = "../", features = ["ariadne"]}
ariadne = {version="0.3.0"}

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"

[[bin]]
name = "tfmtools"
path = "src/tfmtools.rs"

[[bin]]
name = "tftopl"
path = "src/tftopl.rs"
