[package]
name = "texcraft"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version="3.0.0-beta.5", default-features=false, features=["std", "derive"]}

texlang-core = { path = "../texlang-core" }

texlang-stdlib = { path = "../texlang-stdlib", features = ["repl"]}

anyhow = "1.0"

colored = "2"