(FAMILY CMR)
(FACE O352)
(SEVENBITSAFEFLAG TRUEE H)
(COMMENT OTHER SIZES ARE MULTIPLES OF DESIGNSIZ)
            (LIGTABLE
               (LABEL C X)
   (KRN C Y D 1.0)
   (KRN C Y D 2.0)
   (STOP)
               (LABEL C a)
               (LIG C b C c)
               (SKIP D 1)
               (LABEL C p)
               (LIG C q C r)
               (STOP)
               (LIG C s C t)
               (LIG C t C u)
               (STOP)
               )

(CHARACTER C a (CHARWD D 10.0))
(CHARACTER C b (CHARWD D 10.0))
(CHARACTER C c (CHARWD D 10.0))
(CHARACTER C p (CHARWD D 10.0))
(CHARACTER C q (CHARWD D 10.0))
(CHARACTER C r (CHARWD D 10.0))
(CHARACTER C s (CHARWD D 10.0))
(CHARACTER C t (CHARWD D 10.0))
(CHARACTER C u (CHARWD D 10.0))
(CHARACTER C X (CHARWD D 10.0))
(CHARACTER C Y (CHARWD D 10.0))