(FAMILY CMR)
(FACE O 352)
(CODINGSCHEME UNSPECIFIED)
(DESIGNSIZE R 10.0)
(COMMENT DESIGNSIZE IS IN POINTS)
(COMMENT OTHER SIZES ARE MULTIPLES OF DESIGNSIZE)
(CHECKSUM O 10750271273)
(SEVENBITSAFEFLAG TRUE)
(LIGTABLE
   (LABEL C X)
   (KRN C Y R 1.0)
   (KRN C Y R 2.0)
   (STOP)
   (LABEL C a)
   (LIG C b C c)
   (SKIP D 1)
   (LABEL C p)
   (LIG C q C r)
   (STOP)
   (LIG C s C t)
   (LIG C t C u)
   (STOP)
   )
(CHARACTER C X
   (CHARWD R 10.0)
   (COMMENT
      (KRN C Y R 1.0)
      (KRN C Y R 2.0)
      )
   )
(CHARACTER C Y
   (CHARWD R 10.0)
   )
(CHARACTER C a
   (CHARWD R 10.0)
   (COMMENT
      (LIG C b C c)
      (LIG C s C t)
      (LIG C t C u)
      )
   )
(CHARACTER C b
   (CHARWD R 10.0)
   )
(CHARACTER C c
   (CHARWD R 10.0)
   )
(CHARACTER C p
   (CHARWD R 10.0)
   (COMMENT
      (LIG C q C r)
      )
   )
(CHARACTER C q
   (CHARWD R 10.0)
   )
(CHARACTER C r
   (CHARWD R 10.0)
   )
(CHARACTER C s
   (CHARWD R 10.0)
   )
(CHARACTER C t
   (CHARWD R 10.0)
   )
(CHARACTER C u
   (CHARWD R 10.0)
   )
