//! Lig/kern programming.
//!
//! TFM files can include information about ligatures and kerns.
//! A [ligature](https://en.wikipedia.org/wiki/Ligature_(writing))
//!     is a special character that can replace two or more adjacent characters.
//! For example, the pair of characters ae can be replaced by the æ ligature which is a single character.
//! A [kern](https://en.wikipedia.org/wiki/Kerning) is special space inserted between
//!     two adjacent characters to align them better.
//! For example, a kern can be inserted between A and V to compensate for the large
//!     amount of space created by the specific combination of these two characters.
//!
//! ## The lig/kern programming language
//!
//! TFM provides ligature and kern data in the form of
//!     "instructions in a simple programming language that explains what to do for special letter pairs"
//!     (quoting TFtoPL.2014.13).
//! This lig/kern programming language can be used to specify instructions like
//!     "replace the pair (a,e) by æ" and
//!     "insert a kern of width -0.1pt between the pair (A,V)".
//! But it can also specify more complex behaviors.
//! For example, a lig/kern program can specify "replace the pair (x,y) by the pair (z,y)".
//!
//! In general for any pair of characters (x,y) the program specifies zero or one lig/kern instructions.
//! After this instruction is executed, there may be a new
//!     pair of characters remaining, as in the (x,y) to (z,y) instruction.
//! The lig/kern instruction for this pair is then executed, if it exists.
//! This process continues until there are no more instructions left to run.
//!
//! Lig/kern instructions are represented in this module by the [`lang::Instruction`] type.
//!
//! ## Related code by Knuth
//!
//! The TFtoPL and PLtoTF programs don't contain any code for running lig/kern programs.
//! They only contain logic for translating between the `.tfm` and `.pl`
//!     formats for lig/kern programs, and for doing some validation as described below.
//! Lig/kern programs are actually executed in TeX; see KnuthTeX.2021.1032-1040.
//!
//! One of the challenges with lig/kern programs is that they can contain infinite loops.
//! Here is a simple example of a lig/kern program with two instruction and an infinite loop:
//!
//! - Replace (x,y) with (z,y) (in property list format, `(LABEL C x)(LIG/ C y C z)`)
//! - Replace (z,y) with (x,y) (in property list format, `(LABEL C z)(LIG/ C y C x)`)
//!
//! When this program runs (x,y) will be swapped with (z,y) ad infinitum.
//! See TFtoPL.2014.88 for more examples.
//!
//! Both TFtoPL and PLtoTF contain code that checks that a lig/kern program
//!     does not contain infinite loops (TFtoPL.2014.88-95 and PLtoTF.2014.116-125).
//! The algorithm for detecting infinite loops is a topological sorting algorithm
//!     over a graph where each node is a pair of characters.
//! However it's a bit complicated because the full graph cannot be constructed without
//!     running the lig/kern program.
//!
//! TeX does not check for infinite loops, presumably under the assumption that any `.tfm` file will have
//!     been generated by PLtoTF and thus already validated.
//! However TeX does check for interrupts when executing lig/kern programs so that
//!     at least a user can terminate TeX if an infinite loop is hit.
//! (See the `check_interrupt` line in KnuthTeX.2021.1040.)
//!
//! ## Functionality in this module
//!
//! This module handles lig/kern programs in a different way,
//!     inspired by the ["parse don't validate"](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/)
//!     philosophy.
//! This module is able to represent raw lig/kern programs as a vector of [`lang::Instruction`] values.
//! But can also _compile_ lig/kern programs (into a [`CompiledProgram`]).
//! This compilation process essentially executes the lig/kern program for every possible character pair.
//! The result is a map from each character pair to the full list of
//!     replacement characters and kerns for that pair.
//! If there is an infinite loop in the program this compilation will naturally fail.
//! The compiled program is thus a "parsed" version of the lig/kern program
//!     and it is impossible for infinite loops to appear in it.
//!
//! An advantage of this model is that the lig/kern program does not need to be repeatedly
//!     executed in the main hot loop of TeX.
//! This may make TeX faster.
//! However the compiled lig/kern program does have a larger memory footprint than the raw program,
//!     and so it may be slower if TeX is memory bound.

mod compiler;
use crate::ligkern::compiler::Replacement;
use crate::Char;
use crate::FixWord;
use std::collections::HashMap;
use std::rc::Rc;
pub mod lang;

/// A compiled lig/kern program.
///
/// The default value is an empty program with no kerns or ligatures.
#[derive(Clone, Debug, Default)]
pub struct CompiledProgram {
    right_boundary_char: Option<Char>,
    replacements: HashMap<(Option<Char>, Char), compiler::Replacement>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
enum IntermediateOp {
    // Emit the kern.
    Kern(common::Scaled),
    // Emit the char in the payload.
    C(compiler::C),
}

impl CompiledProgram {
    /// Compile a lig/kern program.
    pub fn compile(
        program: &lang::Program,
        design_size: FixWord,
        kerns: &[FixWord],
        entrypoints: HashMap<Char, u16>,
    ) -> (CompiledProgram, Vec<InfiniteLoopError>) {
        compiler::compile(program, design_size, kerns, &entrypoints)
    }

    /// Compile a lig/kern program from a PL file.
    pub fn compile_from_pl_file(
        pl_file: &super::pl::File,
    ) -> (CompiledProgram, Vec<InfiniteLoopError>) {
        let entrypoints = pl_file.lig_kern_entrypoints(false);
        // The kerns array, which is used for KernAtIndex operations, is empty
        // because PL files do not have such operations.
        CompiledProgram::compile(
            &pl_file.lig_kern_program,
            pl_file.header.design_size,
            &[],
            entrypoints,
        )
    }

    /// Compile a lig/kern program from a TFM file.
    pub fn compile_from_tfm_file(
        tfm_file: &mut super::File,
    ) -> (CompiledProgram, Vec<InfiniteLoopError>) {
        let entrypoints: HashMap<Char, u16> = tfm_file
            .lig_kern_entrypoints()
            .into_iter()
            .filter_map(|(c, e)| {
                tfm_file
                    .lig_kern_program
                    .unpack_entrypoint(e)
                    .ok()
                    .map(|e| (c, e))
            })
            .collect();
        CompiledProgram::compile(
            &tfm_file.lig_kern_program,
            tfm_file.header.design_size,
            &tfm_file.kerns,
            entrypoints,
        )
    }

    pub fn has_replacement(&self, left_char: Option<char>, right_char: Option<char>) -> bool {
        self.get_replacement_utf8(left_char, right_char).is_some()
    }

    fn get_replacement(
        &self,
        left_char: Option<Char>,
        right_char: Option<Char>,
    ) -> Option<&Replacement> {
        let right_char = match right_char {
            None => self.right_boundary_char?,
            Some(c) => c,
        };
        self.replacements.get(&(left_char, right_char))
    }

    fn get_replacement_utf8(
        &self,
        left_char: Option<char>,
        right_char: Option<char>,
    ) -> Option<&Replacement> {
        let left_char = match left_char {
            None => None,
            Some(c) => {
                let Ok(c) = c.try_into() else {
                    return None;
                };
                Some(c)
            }
        };
        let right_char = match right_char {
            None => None,
            Some(c) => {
                let Ok(c) = c.try_into() else {
                    return None;
                };
                Some(c)
            }
        };
        self.get_replacement(left_char, right_char)
    }

    /// Returns an iterator over all pairs `(char,char)` that have a replacement
    ///     specified in the lig/kern program.
    pub fn all_pairs_with_replacements(&self) -> Vec<(Option<Char>, Char)> {
        let mut v: Vec<(Option<Char>, Char)> = self.replacements.keys().copied().collect();
        v.sort();
        v
    }

    /// Returns whether this program is seven-bit safe.
    ///
    /// A lig/kern program is seven-bit safe if the replacement for any
    ///     pair of seven-bit safe characters
    ///     consists only of seven-bit characters.
    /// Conversely a program is seven-bit unsafe if there is a
    ///     pair of seven-bit characters whose replacement
    ///     contains a non-seven-bit character.
    pub fn is_seven_bit_safe(&self) -> bool {
        self.all_pairs_with_replacements()
            .into_iter()
            .filter(|(l, r)| l.map(|c| c.is_seven_bit()).unwrap_or(true) && r.is_seven_bit())
            .flat_map(|(l, r)| self.get_replacement(l, Some(r)))
            .all(|rep| {
                rep.0.iter().all(|op| match op {
                    IntermediateOp::Kern(_) => true,
                    IntermediateOp::C(c) => c.c.is_seven_bit(),
                }) && rep.1.c.is_seven_bit()
            })
    }

    pub fn run_iter<'a>(
        &'a self,
        word: &'a str,
        right_boundary_override: Option<char>,
    ) -> RunIter<'a> {
        RunIter {
            program: self,
            word: word.chars(),
            consumes_left: true,
            intermediate_ops: &[],
            next_left: NextLeft::Boundary,
            ligature: None,
            left: None,
            right: None,
            right_boundary_override,
        }
    }
}

#[derive(PartialEq, Debug)]
pub enum RunItem {
    Char(char),
    Kern(common::Scaled),
    Ligature(Ligature),
}

#[derive(Default)]
struct PendingLigature {
    s: String,
    includes_left_boundary: bool,
    includes_right_boundary: bool,
}
impl PendingLigature {
    fn into_ligature(self, c: char) -> Ligature {
        Ligature {
            c,
            original: self.s.into(),
            includes_left_boundary: self.includes_left_boundary,
            includes_right_boundary: self.includes_right_boundary,
        }
    }
}

pub struct RunIter<'a> {
    program: &'a CompiledProgram,
    word: std::str::Chars<'a>,
    consumes_left: bool,
    intermediate_ops: &'a [IntermediateOp],
    next_left: NextLeft,
    ligature: Option<PendingLigature>,
    left: Option<char>,
    right: Option<char>,
    right_boundary_override: Option<char>,
}

#[derive(Debug)]
enum NextLeft {
    Boundary,
    Char(char),
    Lig(char),
    None,
}

impl<'a> RunIter<'a> {
    pub fn is_separation_point(&self) -> bool {
        self.intermediate_ops.is_empty()
            && match self.next_left {
                NextLeft::Lig(_) => false,
                _ => true,
            }
    }
}

impl<'a> Iterator for RunIter<'a> {
    type Item = RunItem;

    fn next(&mut self) -> Option<Self::Item> {
        if let Some((op, tail)) = self.intermediate_ops.split_first() {
            self.intermediate_ops = tail;
            return Some(match op {
                IntermediateOp::Kern(kern) => RunItem::Kern(*kern),
                IntermediateOp::C(compiler::C { c, is_lig: false }) => {
                    self.consumes_left = false;
                    match self.ligature.take() {
                        Some(l) => {
                            // This happens when left is a ligature.
                            RunItem::Ligature(l.into_ligature((*c).into()))
                        }
                        None => RunItem::Char((*c).into()),
                    }
                }
                IntermediateOp::C(compiler::C { c, is_lig: true }) => {
                    let mut s = self.ligature.take().unwrap_or_default();
                    if self.consumes_left {
                        if let Some(left) = self.left {
                            s.s.push(left);
                        } else {
                            s.includes_left_boundary = true;
                        }
                    }
                    self.consumes_left = false;
                    if self.right.is_none() {
                        s.includes_right_boundary = matches!(self.next_left, NextLeft::None)
                            && match (tail.get(0), tail.get(1)) {
                                (None, None) | (Some(IntermediateOp::Kern(_)), None) => true,
                                _ => false,
                            };
                    }
                    RunItem::Ligature(s.into_ligature((*c).into()))
                }
            });
        };
        let (left, left_in_original): (Option<char>, bool) = match &self.next_left {
            NextLeft::Boundary => (None, true),
            NextLeft::Char(c) => (Some(*c), true),
            NextLeft::Lig(op) => match (op, self.right) {
                (c, Some(right)) => {
                    let s = self.ligature.get_or_insert_default();
                    if self.consumes_left {
                        if let Some(left) = self.left {
                            s.s.push(left);
                        } else {
                            s.includes_left_boundary = true;
                        }
                    }
                    s.s.push(right);
                    (Some((*c).into()), false)
                }
                (c, None) => {
                    let mut s = self.ligature.take().unwrap_or_default();
                    if self.consumes_left {
                        if let Some(left) = self.left {
                            s.s.push(left);
                        } else {
                            s.includes_left_boundary = true;
                        }
                    }
                    s.includes_right_boundary = true;
                    let lig = RunItem::Ligature(s.into_ligature((*c).into()));
                    self.next_left = NextLeft::None;
                    return Some(lig);
                }
            },
            NextLeft::None => return None,
        };
        self.left = left;
        self.right = self.word.next();
        if self.left.is_none() && self.right.is_none() {
            // TODO: remove this check?
            return None;
        }
        let right_for_lookup = match self.right {
            Some(r) => Some(r),
            None => self.right_boundary_override,
        };
        // self.left is None if we're at the left boundary
        // self.right is None if we're at the right boundary
        match self
            .program
            .get_replacement_utf8(self.left, right_for_lookup)
        {
            Some(replacement) => {
                self.consumes_left = left_in_original;
                self.intermediate_ops = &replacement.0;
                self.next_left = match (replacement.1.is_lig, self.right) {
                    (false, None) => NextLeft::None,
                    (false, Some(_)) => NextLeft::Char(replacement.1.c.into()),
                    (true, _) => NextLeft::Lig(replacement.1.c.into()),
                };
            }
            None => {
                let old_left = self.left;
                self.left = self.right;
                self.next_left = match self.right {
                    None => NextLeft::None,
                    Some(right) => NextLeft::Char(right),
                };
                if let Some(left) = old_left {
                    return Some(match self.ligature.take() {
                        Some(l) => RunItem::Ligature(l.into_ligature(left)),
                        None => RunItem::Char(left),
                    });
                }
            }
        }
        self.next()
    }
}

#[derive(PartialEq, Debug)]
pub struct Ligature {
    pub c: char,
    pub original: Rc<str>,
    pub includes_left_boundary: bool,
    pub includes_right_boundary: bool,
}

/// An error returned from lig/kern compilation.
///
/// TODO: rename Cycle everywhere including the docs
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InfiniteLoopError {
    /// The pair of characters the starts the infinite loop.
    pub starting_pair: (Option<Char>, Char),
}

impl InfiniteLoopError {
    pub fn pltotf_message(&self) -> String {
        let left = match self.starting_pair.0 {
            Some(c) => format!["'{:03o}", c.0],
            None => "boundary".to_string(),
        };
        format!(
            "Infinite ligature loop starting with {} and '{:03o}!",
            left, self.starting_pair.1 .0
        )
    }
    pub fn pltotf_section(&self) -> u8 {
        125
    }
}

/// One step in a lig/kern infinite loop.
///
/// A vector of these steps is returned in a [`InfiniteLoopError`].
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InfiniteLoopStep {
    /// The index of the instruction to apply in this step.
    pub instruction_index: usize,
    /// The replacement text after applying this step.
    ///
    /// The boolean specifies whether the replacement begins with the
    /// left boundary char.
    pub post_replacement: (bool, Vec<Char>),
    /// The position of the cursor after applying this step.
    pub post_cursor_position: usize,
}

#[cfg(test)]
mod tests {
    use common::Scaled;

    use super::Ligature as L;
    use super::*;
    use pretty_assertions::assert_eq;

    const LIGAROO: &'static str = include_str!["ligaroo.plst"];

    fn run_test(program: &str, input: &str, want: Vec<RunItem>) {
        let source = LIGAROO.replace("(LIGTABLE", &format!["(LIGTABLE\n{program}"]);
        let pl_file = crate::pl::File::from_pl_source_code(&source).0;

        if std::env::var("TEXCRAFT_VERIFY").unwrap_or_default() == "tex" {
            verify_against_tex(pl_file, input, want);
            return;
        }

        let program = CompiledProgram::compile_from_pl_file(&pl_file).0;
        let got: Vec<RunItem> = program.run_iter(input, None).collect();
        assert_eq!(got, want);
    }

    /// Verify the expected output of a test case against a real TeX engine.
    ///
    /// The property list file is converted to a TFM file, TeX builds an
    /// `\hbox` from the input word set in a font backed by that TFM file,
    /// and the box contents (dumped with `\showbox`) are parsed back into
    /// run items and compared to the expected ones.
    fn verify_against_tex(pl_file: crate::pl::File, input: &str, want: Vec<RunItem>) {
        let tfm_file: crate::File = pl_file.into();
        let stdout = run_tex(&tfm_file.serialize(), input);
        let got = parse_showbox_output(&stdout);
        let want: Vec<RunItem> = want.into_iter().map(normalize_for_tex).collect();
        assert_eq!(got, want);
    }

    /// Run the `tex` binary on an `\hbox` containing the input word, set in
    /// a font backed by the provided TFM bytes, and return the terminal
    /// output which includes a `\showbox` dump of the box.
    fn run_tex(tfm_bytes: &[u8], input: &str) -> String {
        let mut dir = std::env::temp_dir();
        dir.push("texcraft_tfm_ligkern");
        // The thread name is the name of the unit test being run, so tests
        // running in parallel get distinct directories.
        dir.push(
            std::thread::current()
                .name()
                .unwrap_or("texcraft_unknown_thread_name")
                .replace("::", "__"),
        );
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("ligaroo.tfm"), tfm_bytes).unwrap();

        let tex_source = format!(
            r"\nonstopmode
\tracingonline=1
\showboxbreadth=1000000
\showboxdepth=100
\font\ligkernfont=ligaroo
\ligkernfont
\setbox253=\hbox{{{input}}}
\showbox253
\end
"
        );
        let input_path = dir.join("tex-input.tex");
        std::fs::write(&input_path, tex_source).unwrap();

        let output = std::process::Command::new("tex")
            .current_dir(&dir)
            // By default TeX wraps terminal output at 79 characters, which
            // would split long box dump lines.
            .env("max_print_line", "10000")
            .arg(&input_path)
            .output()
            .expect("failed to run the `tex` binary");
        // The exit status is not checked: `\showbox` counts as an error in
        // TeX's book-keeping ("! OK.") and makes the exit status non-zero.
        String::from_utf8(output.stdout).expect("stdout of TeX is utf-8")
    }

    /// Parse the contents of the box dumped with `\showbox253` into run items.
    fn parse_showbox_output(stdout: &str) -> Vec<RunItem> {
        let mut lines = stdout.lines();
        for line in lines.by_ref() {
            if line.starts_with(r"> \box253=") {
                break;
            }
        }
        let dimens_line = lines.next().expect(r"box dump contains an \hbox line");
        assert!(
            dimens_line.starts_with(r"\hbox("),
            r"expected an \hbox dimensions line, got {dimens_line:?}"
        );
        // The box contents are the following lines, prefixed with a period
        // because they are one level deep in the dumped box.
        lines
            .map_while(|line| line.strip_prefix('.'))
            .map(parse_run_item)
            .collect()
    }

    /// Parse one line of the box dump into a run item.
    fn parse_run_item(line: &str) -> RunItem {
        // Kern lines look like `\kern1.0` (or `\kern 1.0` for explicit kerns).
        if let Some(width) = line.strip_prefix(r"\kern") {
            let width = common::Scaled::parse_no_units(width.trim())
                .expect("kern width fits in a scaled number");
            return RunItem::Kern(width);
        }
        // Character lines look like `\ligkernfont A`, and ligature lines
        // like `\ligkernfont 1 (ligature AB)`.
        let tail = line
            .strip_prefix(r"\ligkernfont ")
            .expect(r"box content line is a \kern or a character in the test font");
        let parse_char = |s: &str| {
            let mut chars = s.chars();
            let c = chars.next().expect("a character follows the font name");
            assert_eq!(chars.next(), None, "expected a single character in {s:?}");
            c
        };
        match tail.split_once(" (ligature ") {
            None => RunItem::Char(parse_char(tail)),
            Some((c, original)) => {
                let original = original
                    .strip_suffix(')')
                    .expect("ligature original chars end with `)`");
                RunItem::Ligature(Ligature {
                    c: parse_char(c),
                    original: original.into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                })
            }
        }
    }

    /// Normalize a run item to the form in which it appears in TeX's box dump.
    ///
    /// TeX's box display marks a boundary character in a ligature's original
    /// characters with a `|`. A `|` next to an empty original is ambiguous
    /// between the left and the right boundary, so instead of parsing the
    /// markers back into the boundary fields, the comparison happens on the
    /// marked-up original characters with the boundary fields cleared.
    fn normalize_for_tex(item: RunItem) -> RunItem {
        match item {
            RunItem::Ligature(ligature) => {
                let mut original = String::new();
                if ligature.includes_left_boundary {
                    original.push('|');
                }
                original.push_str(&ligature.original);
                if ligature.includes_right_boundary {
                    original.push('|');
                }
                RunItem::Ligature(Ligature {
                    c: ligature.c,
                    original: original.into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                })
            }
            item => item,
        }
    }

    macro_rules! tests {
        ( $(
            ($name: ident, $program: expr, $input: expr, $want: expr, ),
        )+ ) => { $(
            #[test]
            fn $name() {
                #[allow(unused_imports)]
                use RunItem::*;
                let program = $program;
                let input = $input;
                let want = $want;
                run_test(program, input, want);
            }
        )+ };
    }

    tests!(
        (empty_input, "", "", vec![],),
        // AB -> ^1
        (
            single_lig_1,
            "
                (LABEL C A)
                (LIG C B C 1)
                (KRN C 1 R 0.1)
                (STOP)

                (LABEL C 1)
                (KRN C B R 0.3)
                (STOP)
            ",
            "AB",
            vec![Ligature(L {
                c: '1',
                original: "AB".into(),
                includes_left_boundary: false,
                includes_right_boundary: false,
            })],
        ),
        // AB -> ^A1
        (
            single_lig_2,
            "
                (LABEL C A)
                (/LIG C B C 1)
                (KRN C 1 R 0.1)
                (STOP)

                (LABEL C 1)
                (KRN C B R 0.3)
                (STOP)
            ",
            "AB",
            vec![
                Char('A'),
                Kern(Scaled::ONE),
                Ligature(L {
                    c: '1',
                    original: "B".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                })
            ],
        ),
        // AB -> A^1
        (
            single_lig_3,
            "
                (LABEL C A)
                (/LIG> C B C 1)
                (KRN C 1 R 0.1)
                (STOP)

                (LABEL C 1)
                (KRN C B R 0.3)
                (STOP)
            ",
            "AB",
            vec![
                Char('A'),
                Ligature(L {
                    c: '1',
                    original: "B".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
            ],
        ),
        // AB -> ^1B
        (
            single_lig_4,
            "
                (LABEL C A)
                (LIG/ C B C 1)
                (KRN C 1 R 0.1)
                (STOP)

                (LABEL C 1)
                (KRN C B R 0.3)
                (STOP)
            ",
            "AB",
            vec![
                Ligature(L {
                    c: '1',
                    original: "A".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Kern(Scaled::ONE * 3),
                Char('B'),
            ],
        ),
        // AB -> 1^B
        (
            single_lig_5,
            "
                (LABEL C A)
                (LIG/> C B C 1)
                (KRN C 1 R 0.1)
                (STOP)

                (LABEL C 1)
                (KRN C B R 0.3)
                (STOP)
            ",
            "AB",
            vec![
                Ligature(L {
                    c: '1',
                    original: "A".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Char('B'),
            ],
        ),
        // AB -> ^A1B
        (
            single_lig_6,
            "
                (LABEL C A)
                (/LIG/ C B C 1)
                (KRN C 1 R 0.1)
                (STOP)

                (LABEL C 1)
                (KRN C B R 0.3)
                (STOP)
            ",
            "AB",
            vec![
                Char('A'),
                Kern(Scaled::ONE),
                Ligature(L {
                    c: '1',
                    original: "".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Kern(Scaled::ONE * 3),
                Char('B'),
            ],
        ),
        // AB -> A^1B
        (
            single_lig_7,
            "
                (LABEL C A)
                (/LIG/> C B C 1)
                (KRN C 1 R 0.1)
                (STOP)

                (LABEL C 1)
                (KRN C B R 0.3)
                (STOP)
            ",
            "AB",
            vec![
                Char('A'),
                Ligature(L {
                    c: '1',
                    original: "".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Kern(Scaled::ONE * 3),
                Char('B'),
            ],
        ),
        // AB -> A1^B
        (
            single_lig_8,
            "
                (LABEL C A)
                (/LIG/>> C B C 1)
                (KRN C 1 R 0.1)
                (STOP)

                (LABEL C 1)
                (KRN C B R 0.3)
                (STOP)
            ",
            "AB",
            vec![
                Char('A'),
                Ligature(L {
                    c: '1',
                    original: "".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Char('B'),
            ],
        ),
        // AB -> A^B
        // This is the same as single_lig_5, but the replacement character
        // is the same as the character that is removed. In theory lig(A, A)
        // could be replaced by char(A), and this test verifies that it is not.
        (
            no_op_lig,
            "
                (LABEL C A)
                (LIG/> C B C A)
                (STOP)
            ",
            "AB",
            vec![
                Ligature(L {
                    c: 'A',
                    original: "A".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Char('B'),
            ],
        ),
        // AB -> ^1, 1C -> ^2
        (
            multiple_lig_1,
            "
                (LABEL C A)
                (LIG C B C 1)

                (LABEL C 1)
                (LIG C C C 2)
                (STOP)
            ",
            "ABC",
            vec![Ligature(L {
                c: '2',
                original: "ABC".into(),
                includes_left_boundary: false,
                includes_right_boundary: false,
            }),],
        ),
        // AB -> ^A1B, 1B -> 2
        (
            multiple_lig_2,
            "
                (LABEL C A)
                (/LIG/ C B C 1)
                (LABEL C 1)
                (LIG C B C 2)
                (STOP)
            ",
            "AB",
            vec![
                Char('A'),
                Ligature(L {
                    c: '2',
                    original: "B".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
            ],
        ),
        // AA -> 1^A multiple times
        (
            multiple_lig_3,
            "
                (LABEL C A)
                (LIG/ C A C 1)
                (STOP)
            ",
            "AAAAA",
            vec![
                Ligature(L {
                    c: '1',
                    original: "A".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Ligature(L {
                    c: '1',
                    original: "A".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Ligature(L {
                    c: '1',
                    original: "A".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Ligature(L {
                    c: '1',
                    original: "A".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Char('A'),
            ],
        ),
        // AA -> ^A multiple times
        (
            multiple_lig_4,
            "
                (LABEL C A)
                (LIG C A C A)
                (STOP)
            ",
            "AAAAAA",
            vec![Ligature(L {
                c: 'A',
                original: "AAAAAA".into(),
                includes_left_boundary: false,
                includes_right_boundary: false,
            }),],
        ),
        // AB -> ^A1, A1 -> ^21
        (
            multiple_lig_5,
            "
                (LABEL C A)
                (/LIG C B C 1)
                (LIG/ C 1 C 2)
                (STOP)
            ",
            "AB",
            vec![
                Ligature(L {
                    c: '2',
                    original: "A".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Ligature(L {
                    c: '1',
                    original: "B".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
            ],
        ),
        // AB -> ^A1, A1 -> ^21, 21 -> 3
        (
            multiple_lig_6,
            "
                (LABEL C A)
                (/LIG C B C 1)
                (LIG/ C 1 C 2)
                (LABEL C 2)
                (LIG C 1 C 3)
                (STOP)
            ",
            "AB",
            vec![Ligature(L {
                c: '3',
                original: "AB".into(),
                includes_left_boundary: false,
                includes_right_boundary: false,
            })],
        ),
        // AB -> ^1, 1C -> 12^C
        (
            multiple_lig_7,
            "
                (LABEL C A)
                (LIG C B C 1)
                (STOP)

                (LABEL C 1)
                (/LIG/>> C C C 2)
                (STOP)
            ",
            "ABC",
            vec![
                Ligature(L {
                    c: '1',
                    original: "AB".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Ligature(L {
                    c: '2',
                    original: "".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Char('C'),
            ],
        ),
        (
            kern_after_lig_1,
            "
                (LABEL C A)
                (LIG C B C 1)
                (STOP)

                (LABEL C 1)
                (KRN C C R 0.1)
            ",
            "ABC",
            vec![
                Ligature(L {
                    c: '1',
                    original: "AB".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Kern(Scaled::ONE),
                Char('C'),
            ],
        ),
        (
            kern_after_lig_2,
            "
                (LABEL C A)
                (LIG C B C 1)
                (STOP)

                (LABEL C 1)
                (KRN C A R 0.1)
            ",
            "ABAB",
            vec![
                Ligature(L {
                    c: '1',
                    original: "AB".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Kern(Scaled::ONE),
                Ligature(L {
                    c: '1',
                    original: "AB".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
            ],
        ),
        (
            left_boundary_char_1,
            "
                (LABEL BOUNDARYCHAR)
                (LIG C A C 1)
            ",
            "A",
            vec![Ligature(L {
                c: '1',
                original: "A".into(),
                includes_left_boundary: true,
                includes_right_boundary: false,
            }),],
        ),
        (
            left_boundary_char_2,
            "
                (LABEL BOUNDARYCHAR)
                (/LIG/ C A C 1)
                (/LIG/ C 1 C 2)
            ",
            "A",
            vec![
                Ligature(L {
                    c: '2',
                    original: "".into(),
                    includes_left_boundary: true,
                    includes_right_boundary: false,
                }),
                Ligature(L {
                    c: '1',
                    original: "".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Char('A'),
            ],
        ),
        (
            left_boundary_char_3,
            "
                (LABEL BOUNDARYCHAR)
                (/LIG/ C A C 1)
            ",
            "A",
            vec![
                Ligature(L {
                    c: '1',
                    original: "".into(),
                    includes_left_boundary: true,
                    includes_right_boundary: false,
                }),
                Char('A'),
            ],
        ),
        // |A -> ^|1
        (
            left_boundary_char_4,
            "
                (LABEL BOUNDARYCHAR)
                (/LIG C A C 1)
            ",
            "A",
            vec![Ligature(L {
                c: '1',
                original: "A".into(),
                includes_left_boundary: true,
                includes_right_boundary: false,
            }),],
        ),
        // |A -> |^1
        (
            left_boundary_char_5,
            "
                (LABEL BOUNDARYCHAR)
                (/LIG> C A C 1)
            ",
            "A",
            vec![Ligature(L {
                c: '1',
                original: "A".into(),
                includes_left_boundary: true,
                includes_right_boundary: false,
            }),],
        ),
        // |A -> ^1A
        (
            left_boundary_char_6,
            "
                (LABEL BOUNDARYCHAR)
                (LIG/ C A C 1)
            ",
            "A",
            vec![
                Ligature(L {
                    c: '1',
                    original: "".into(),
                    includes_left_boundary: true,
                    includes_right_boundary: false,
                }),
                Char('A'),
            ],
        ),
        // |A -> 1^A
        (
            left_boundary_char_7,
            "
                (LABEL BOUNDARYCHAR)
                (LIG/> C A C 1)
            ",
            "A",
            vec![
                Ligature(L {
                    c: '1',
                    original: "".into(),
                    includes_left_boundary: true,
                    includes_right_boundary: false,
                }),
                Char('A'),
            ],
        ),
        // |A -> |^1A
        (
            left_boundary_char_8,
            "
                (LABEL BOUNDARYCHAR)
                (/LIG/> C A C 1)
            ",
            "A",
            vec![
                Ligature(L {
                    c: '1',
                    original: "".into(),
                    includes_left_boundary: true,
                    includes_right_boundary: false,
                }),
                Char('A'),
            ],
        ),
        // |A -> |1^A
        (
            left_boundary_char_9,
            "
                (LABEL BOUNDARYCHAR)
                (/LIG/>> C A C 1)
            ",
            "A",
            vec![
                Ligature(L {
                    c: '1',
                    original: "".into(),
                    includes_left_boundary: true,
                    includes_right_boundary: false,
                }),
                Char('A'),
            ],
        ),
        (
            right_boundary_char_lig_1,
            "
                (LABEL C A)
                (LIG C R C 1)
                (STOP)
            ",
            "A",
            vec![Ligature(L {
                c: '1',
                original: "A".into(),
                includes_left_boundary: false,
                includes_right_boundary: true,
            }),],
        ),
        // AR -> ^AB
        (
            right_boundary_char_lig_2,
            "
                (LABEL C A)
                (/LIG C R C B)
                (STOP)
            ",
            "A",
            vec![
                Char('A'),
                Ligature(L {
                    c: 'B',
                    original: "".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: true,
                }),
            ],
        ),
        // AR -> A^B
        (
            right_boundary_char_lig_3,
            "
                (LABEL C A)
                (/LIG> C R C B)
                (STOP)
            ",
            "A",
            vec![
                Char('A'),
                Ligature(L {
                    c: 'B',
                    original: "".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: true,
                }),
            ],
        ),
        (
            right_boundary_char_lig_4,
            "
                (LABEL C A)
                (/LIG/ C R C B)
                (STOP)
            ",
            "A",
            vec![
                Char('A'),
                Ligature(L {
                    c: 'B',
                    original: "".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: true,
                }),
            ],
        ),
        // AR -> ^BR
        (
            right_boundary_char_lig_5,
            "
                (LABEL C A)
                (LIG/ C R C B)
                (STOP)
            ",
            "A",
            vec![Ligature(L {
                c: 'B',
                original: "A".into(),
                includes_left_boundary: false,
                includes_right_boundary: true,
            }),],
        ),
        // AR -> BR^
        (
            right_boundary_char_lig_6,
            "
                (LABEL C A)
                (LIG/> C R C B)
                (STOP)
            ",
            "A",
            vec![Ligature(L {
                c: 'B',
                original: "A".into(),
                includes_left_boundary: false,
                includes_right_boundary: true,
            }),],
        ),
        // AR -> A^BR
        (
            right_boundary_char_lig_7,
            "
                (LABEL C A)
                (/LIG/> C R C B)
                (STOP)
            ",
            "A",
            vec![
                Char('A'),
                Ligature(L {
                    c: 'B',
                    original: "".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: true,
                }),
            ],
        ),
        // AR -> AB^R
        (
            right_boundary_char_lig_8,
            "
                (LABEL C A)
                (/LIG/>> C R C B)
                (STOP)
            ",
            "A",
            vec![
                Char('A'),
                Ligature(L {
                    c: 'B',
                    original: "".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: true,
                }),
            ],
        ),
        (
            right_boundary_char_lig_9,
            "
                (LABEL C A)
                (LIG C R C B)
                (LABEL C B)
                (LIG C R C C)
                (STOP)
            ",
            "A",
            vec![Ligature(L {
                c: 'B',
                original: "A".into(),
                includes_left_boundary: false,
                includes_right_boundary: true,
            }),],
        ),
        (
            right_boundary_char_lig_10,
            "
                (LABEL C A)
                (LIG/ C R C B)
                (LABEL C B)
                (LIG/ C R C C)
                (STOP)
            ",
            "A",
            vec![Ligature(L {
                c: 'C',
                original: "A".into(),
                includes_left_boundary: false,
                includes_right_boundary: true,
            }),],
        ),
        (
            right_boundary_char_lig_11,
            "
                (LABEL C A)
                (LIG C R C B)
                (LABEL C B)
                (LIG/ C R C C)
                (STOP)
            ",
            "A",
            vec![Ligature(L {
                c: 'B',
                original: "A".into(),
                includes_left_boundary: false,
                includes_right_boundary: true,
            }),],
        ),
        (
            right_boundary_char_lig_12,
            "
                (LABEL C A)
                (LIG/ C R C B)
                (LABEL C B)
                (LIG C R C C)
                (STOP)
            ",
            "A",
            vec![Ligature(L {
                c: 'C',
                original: "A".into(),
                includes_left_boundary: false,
                includes_right_boundary: true,
            }),],
        ),
        (
            right_boundary_char_kern_1,
            "
                (LABEL C A)
                (KRN C R R 1)
                (STOP)
            ",
            "A",
            vec![Char('A'), Kern(Scaled::ONE * 10),],
        ),
        (
            right_boundary_char_kern_2,
            "
                (LABEL C A)
                (LIG/ C R C B)
                (LABEL C B)
                (LIG/ C R C C)
                (LABEL C C)
                (KRN C R R 1)
                (STOP)
            ",
            "A",
            vec![
                Ligature(L {
                    c: 'C',
                    original: "A".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: true,
                }),
                Kern(Scaled::ONE * 10),
            ],
        ),
        (
            right_boundary_char_kern_3,
            "
                (LABEL C A)
                (LIG C B C C)
                (LABEL C C)
                (KRN C R R 1)
                (STOP)
            ",
            "AB",
            vec![
                Ligature(L {
                    c: 'C',
                    original: "AB".into(),
                    includes_left_boundary: false,
                    includes_right_boundary: false,
                }),
                Kern(Scaled::ONE * 10),
            ],
        ),
    );
}
