//! Lig/kern programming.
//!
//! TFM files can include information about ligatures and kerns.
//! A [ligature](https://en.wikipedia.org/wiki/Ligature_(writing))
//!     is a special character that can replace two or more adjacent characters.
//! For example, the pair of characters ae can be replaced by the æ ligature which is a single character.
//! A [kern](https://en.wikipedia.org/wiki/Kerning) is special space inserted between
//!     two adjacent characters to align them better.
//! For example, a kern can be inserted between A and V to compensate for the large
//!     amount of space created by the specific combination of these two characters.
//!
//! ## The lig/kern programming language
//!
//! TFM provides ligature and kern data in the form of
//!     "instructions in a simple programming language that explains what to do for special letter pairs"
//!     (quoting TFtoPL.2014.13).
//! This lig/kern programming language can be used to specify instructions like
//!     "replace the pair (a,e) by æ" and
//!     "insert a kern of width -0.1pt between the pair (A,V)".
//! But it can also specify more complex behaviors.
//! For example, a lig/kern program can specify "replace the pair (x,y) by the pair (z,y)".
//!
//! In general for any pair of characters (x,y) the program specifies zero or one lig/kern instructions.
//! After this instruction is executed, there may be a new
//!     pair of characters remaining, as in the (x,y) to (z,y) instruction.
//! The lig/kern instruction for this pair is then executed, if it exists.
//! This process continues until there are no more instructions left to run.
//!
//! Lig/kern instructions are represented in this module by the [`lang::Instruction`] type.
//!
//! ## Related code by Knuth
//!
//! The TFtoPL and PLtoTF programs don't contain any code for running lig/kern programs.
//! They only contain logic for translating between the `.tfm` and `.pl`
//!     formats for lig/kern programs, and for doing some validation as described below.
//! Lig/kern programs are actually executed in TeX; see KnuthTeX.2021.1032-1040.
//!
//! One of the challenges with lig/kern programs is that they can contain infinite loops.
//! Here is a simple example of a lig/kern program with two instruction and an infinite loop:
//!
//! - Replace (x,y) with (z,y) (in property list format, `(LABEL C x)(LIG/ C y C z)`)
//! - Replace (z,y) with (x,y) (in property list format, `(LABEL C z)(LIG/ C y C x)`)
//!
//! When this program runs (x,y) will be swapped with (z,y) ad infinitum.
//! See TFtoPL.2014.88 for more examples.
//!
//! Both TFtoPL and PLtoTF contain code that checks that a lig/kern program
//!     does not contain infinite loops (TFtoPL.2014.88-95 and PLtoTF.2014.116-125).
//! The algorithm for detecting infinite loops is a topological sorting algorithm
//!     over a graph where each node is a pair of characters.
//! However it's a bit complicated because the full graph cannot be constructed without
//!     running the lig/kern program.
//!
//! TeX does not check for infinite loops, presumably under the assumption that any `.tfm` file will have
//!     been generated by PLtoTF and thus already validated.
//! However TeX does check for interrupts when executing lig/kern programs so that
//!     at least a user can terminate TeX if an infinite loop is hit.
//! (See the `check_interrupt` line in KnuthTeX.2021.1040.)
//!
//! ## Functionality in this module
//!
//! This module handles lig/kern programs in a different way,
//!     inspired by the ["parse don't validate"](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/)
//!     philosophy.
//! This module is able to represent raw lig/kern programs as a vector of [`lang::Instruction`] values.
//! But can also _compile_ lig/kern programs (into a [`CompiledProgram`]).
//! This compilation process essentially executes the lig/kern program for every possible character pair.
//! The result is a map from each character pair to the full list of
//!     replacement characters and kerns for that pair.
//! If there is an infinite loop in the program this compilation will naturally fail.
//! The compiled program is thus a "parsed" version of the lig/kern program
//!     and it is impossible for infinite loops to appear in it.
//!
//! An advantage of this model is that the lig/kern program does not need to be repeatedly
//!     executed in the main hot loop of TeX.
//! This may make TeX faster.
//! However the compiled lig/kern program does have a larger memory footprint than the raw program,
//!     and so it may be slower if TeX is memory bound.

mod compiler;
use crate::ligkern::compiler::Replacement;
use crate::Char;
use crate::FixWord;
use std::collections::HashMap;
use std::rc::Rc;
pub mod lang;

/// A compiled lig/kern program.
///
/// The default value is an empty program with no kerns or ligatures.
#[derive(Clone, Debug, Default)]
pub struct CompiledProgram {
    replacements: HashMap<(Char, Char), compiler::Replacement>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
enum IntermediateOp {
    // Emit the kern.
    Kern(FixWord),
    // Emit the char in the payload.
    C(compiler::C),
}

impl CompiledProgram {
    /// Compile a lig/kern program.
    pub fn compile(
        program: &lang::Program,
        // TODO: should accept the kerns as a list of Scaled that incorporate the
        // design size
        kerns: &[FixWord],
        entrypoints: HashMap<Char, u16>,
    ) -> (CompiledProgram, Vec<InfiniteLoopError>) {
        compiler::compile(program, kerns, &entrypoints)
    }

    /// Compile a lig/kern program from a PL file.
    pub fn compile_from_pl_file(
        pl_file: &super::pl::File,
    ) -> (CompiledProgram, Vec<InfiniteLoopError>) {
        let entrypoints = pl_file.lig_kern_entrypoints(false);
        // The kerns array, which is used for KernAtIndex operations, is empty
        // because PL files do not have such operations.
        CompiledProgram::compile(&pl_file.lig_kern_program, &[], entrypoints)
    }

    /// Compile a lig/kern program from a TFM file.
    pub fn compile_from_tfm_file(
        tfm_file: &mut super::File,
    ) -> (CompiledProgram, Vec<InfiniteLoopError>) {
        let entrypoints: HashMap<Char, u16> = tfm_file
            .lig_kern_entrypoints()
            .into_iter()
            .filter_map(|(c, e)| {
                tfm_file
                    .lig_kern_program
                    .unpack_entrypoint(e)
                    .ok()
                    .map(|e| (c, e))
            })
            .collect();
        CompiledProgram::compile(&tfm_file.lig_kern_program, &tfm_file.kerns, entrypoints)
    }

    pub(crate) fn get_replacement_utf8(
        &self,
        left_char: char,
        right_char: char,
    ) -> Option<&Replacement> {
        let Ok(left_char) = left_char.try_into() else {
            return None;
        };
        let Ok(right_char) = right_char.try_into() else {
            return None;
        };
        self.replacements.get(&(left_char, right_char))
    }

    /// Returns an iterator over all pairs `(char,char)` that have a replacement
    ///     specified in the lig/kern program.
    pub fn all_pairs_with_replacements(&self) -> impl '_ + Iterator<Item = (Char, Char)> {
        self.replacements.keys().copied()
    }

    /// Returns whether this program is seven-bit safe.
    ///
    /// A lig/kern program is seven-bit safe if the replacement for any
    ///     pair of seven-bit safe characters
    ///     consists only of seven-bit characters.
    /// Conversely a program is seven-bit unsafe if there is a
    ///     pair of seven-bit characters whose replacement
    ///     contains a non-seven-bit character.
    pub fn is_seven_bit_safe(&self) -> bool {
        self.all_pairs_with_replacements()
            .filter(|(l, r)| l.is_seven_bit() && r.is_seven_bit())
            .flat_map(|(l, r)| self.get_replacement_utf8(l.into(), r.into()))
            .all(|rep| {
                rep.0.iter().all(|op| match op {
                    IntermediateOp::Kern(_) => true,
                    IntermediateOp::C(c) => c.c.is_seven_bit(),
                }) && rep.1.c.is_seven_bit()
            })
    }

    /// Run this lig/kern program.
    pub fn run<T: Emitter>(&self, text: &str, emitter: &mut T) {
        let Some(mut left) = text.chars().next() else {
            return;
        };
        let mut left_in_original = true;
        let mut lig_pieces: Option<String> = None;
        let text = &text[left.len_utf8()..];
        let mut iter = text.chars();
        loop {
            let Some(right) = iter.next() else { break };

            match self.get_replacement_utf8(left, right) {
                Some(replacement) => {
                    for op in &replacement.0 {
                        match op {
                            IntermediateOp::Kern(fix_word) => {
                                emitter.emit_kern(fix_word.to_scaled(FixWord::ONE * 10))
                            }
                            IntermediateOp::C(compiler::C {
                                c: char,
                                is_lig: false,
                                consumes_left: _,
                                consumes_right: _,
                            }) => match lig_pieces.take() {
                                Some(l) => {
                                    emitter.emit_ligature((*char).into(), l.into());
                                }
                                None => {
                                    emitter.emit_character((*char).into());
                                }
                            },
                            IntermediateOp::C(compiler::C {
                                c: char,
                                is_lig: true,
                                consumes_left,
                                consumes_right,
                            }) => {
                                dbg!(left_in_original);
                                let mut s = lig_pieces.take().unwrap_or_default();
                                if *consumes_left && left_in_original {
                                    s.push(left);
                                }
                                if *consumes_right {
                                    s.push(right);
                                }
                                emitter.emit_ligature((*char).into(), s.into());
                            }
                        }
                    }
                    if !replacement.1.is_lig {
                        left = (replacement.1.c).into();
                        left_in_original = replacement.1.consumes_right;
                    } else {
                        let mut s = lig_pieces.take().unwrap_or_default();
                        if replacement.1.consumes_left && left_in_original {
                            s.push(left);
                        }
                        if replacement.1.consumes_right {
                            s.push(right);
                        }
                        lig_pieces = Some(s);
                        left = (replacement.1.c).into();
                        left_in_original = false;
                    }
                }
                None => {
                    match lig_pieces.take() {
                        Some(l) => {
                            emitter.emit_ligature(left, l.into());
                        }
                        None => {
                            emitter.emit_character(left);
                        }
                    }
                    left = right;
                    left_in_original = true;
                }
            }
        }
        match lig_pieces.take() {
            Some(l) => {
                emitter.emit_ligature(left, l.into());
            }
            None => {
                emitter.emit_character(left);
            }
        }
    }
}

/// Implementations of this trait determine how characters, kerns and ligatures
/// are handled when running a lig/kern program.
pub trait Emitter {
    fn emit_character(&mut self, c: char);
    fn emit_kern(&mut self, kern: core::Scaled);
    fn emit_ligature(&mut self, c: char, original: Rc<str>);
}

/// An error returned from lig/kern compilation.
///
/// TODO: rename Cycle everywhere including the docs
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InfiniteLoopError {
    /// The pair of characters the starts the infinite loop.
    pub starting_pair: (Option<Char>, Char),
}

impl InfiniteLoopError {
    pub fn pltotf_message(&self) -> String {
        let left = match self.starting_pair.0 {
            Some(c) => format!["'{:03o}", c.0],
            None => "boundary".to_string(),
        };
        format!(
            "Infinite ligature loop starting with {} and '{:03o}!",
            left, self.starting_pair.1 .0
        )
    }
    pub fn pltotf_section(&self) -> u8 {
        125
    }
}

/// One step in a lig/kern infinite loop.
///
/// A vector of these steps is returned in a [`InfiniteLoopError`].
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InfiniteLoopStep {
    /// The index of the instruction to apply in this step.
    pub instruction_index: usize,
    /// The replacement text after applying this step.
    ///
    /// The boolean specifies whether the replacement begins with the
    /// left boundary char.
    pub post_replacement: (bool, Vec<Char>),
    /// The position of the cursor after applying this step.
    pub post_cursor_position: usize,
}

#[cfg(test)]
mod tests {
    use core::Scaled;

    use super::*;

    const LIGAROO: &'static str = include_str!["../../corpus/ligaroo.plst"];

    #[derive(PartialEq, Eq, Debug)]
    enum Element {
        Char(char),
        Kern(core::Scaled),
        Ligature(char, Rc<str>),
    }

    #[derive(Default)]
    struct ElementEmitter(Vec<Element>);

    impl Emitter for ElementEmitter {
        fn emit_character(&mut self, c: char) {
            self.0.push(Element::Char(c))
        }

        fn emit_kern(&mut self, kern: core::Scaled) {
            self.0.push(Element::Kern(kern))
        }

        fn emit_ligature(&mut self, c: char, original: Rc<str>) {
            self.0.push(Element::Ligature(c, original))
        }
    }

    fn run_test(input: &str, want: Vec<Element>) {
        let pl_file = crate::pl::File::from_pl_source_code(&LIGAROO).0;
        let program = CompiledProgram::compile_from_pl_file(&pl_file).0;
        let mut emitter: ElementEmitter = Default::default();
        program.run(input, &mut emitter);
        assert_eq!(emitter.0, want);
    }

    macro_rules! tests {
        ( $(
            ($name: ident, $input: expr, $want: expr, ),
        )+ ) => { $(
            #[test]
            fn $name() {
                use Element::*;
                let input = $input;
                let want = $want;
                run_test(input, want);
            }
        )+ };
    }

    tests!(
        (single_char, "A", vec![Char('A')],),
        // ab -> ^j
        (single_lig_1, "ab", vec![Ligature('j', "ab".into())],),
        // ac -> ^ak
        (
            single_lig_2,
            "ac",
            vec![Char('a'), Kern(Scaled::ONE * 10), Ligature('k', "c".into())],
        ),
        // ad -> a^l
        (
            single_lig_3,
            "ad",
            vec![Char('a'), Ligature('l', "d".into()),],
        ),
        // ae -> ^me
        (
            single_lig_4,
            "ae",
            vec![Ligature('m', "a".into()), Kern(Scaled::ONE * 10), Char('e'),],
        ),
        // af -> n^f
        (
            single_lig_5,
            "af",
            vec![Ligature('n', "a".into()), Char('f'),],
        ),
        // ag -> ^aog
        (
            single_lig_6,
            "ag",
            vec![
                Char('a'),
                Kern(Scaled::ONE * 10),
                Ligature('o', "".into()),
                Kern(Scaled::ONE * 10),
                Char('g'),
            ],
        ),
        // ah -> a^ph
        (
            single_lig_7,
            "ah",
            vec![
                Char('a'),
                Ligature('p', "".into()),
                Kern(Scaled::ONE * 10),
                Char('h'),
            ],
        ),
        // ai -> aq^i
        (
            single_lig_8,
            "ai",
            vec![Char('a'), Ligature('q', "".into()), Char('i'),],
        ),
        // xy -> x^y
        // This is the same as single_lig_3, but the replacement character
        // is the same as the character that is removed. In theory lig(x, x)
        // could be replaced by char(x), and this test verifies that it is not.
        (no_op_lig, "xy", vec![Ligature('x', "x".into()), Char('y'),],),
        // AC -> ^B, BD -> ^E
        (multiple_lig_1, "ACD", vec![Ligature('E', "ACD".into()),],),
        // CE -> ^CDE, DE -> G
        (
            multiple_lig_2,
            "CE",
            vec![Char('C'), Ligature('G', "E".into()),],
        ),
        // EE -> F^E multiple times
        (
            multiple_lig_3,
            "EEEEE",
            vec![
                Ligature('F', "E".into()),
                Ligature('F', "E".into()),
                Ligature('F', "E".into()),
                Ligature('F', "E".into()),
                Char('E'),
            ],
        ),
        // FF -> ^F multiple times
        (
            multiple_lig_4,
            "FFFFFF",
            vec![Ligature('F', "FFFFFF".into()),],
        ),
        // GH -> ^GI, GI -> ^JI
        (
            multiple_lig_5,
            "GH",
            vec![Ligature('J', "G".into()), Ligature('I', "H".into()),],
        ),
        // HA -> ^HB, HB -> ^IB, IB -> C
        (multiple_lig_6, "HA", vec![Ligature('C', "HA".into())],),
        // JA -> ^K, KB -> ^KBC
        (
            multiple_lig_7,
            "JAC",
            vec![
                Ligature('K', "JA".into()),
                Ligature('B', "".into()),
                Char('C'),
            ],
        ),
        (
            kern_after_lig_1,
            "abk",
            vec![
                Ligature('j', "ab".into()),
                Kern(Scaled::ONE * 10),
                Char('k'),
            ],
        ),
        (
            kern_after_lig_2,
            "abab",
            vec![
                Ligature('j', "ab".into()),
                Kern(Scaled::ONE * 10),
                Ligature('j', "ab".into()),
            ],
        ),
    );
}
