# baseURL = "http://texcraft.dev"
languageCode = "en-us"
title = "Texcraft"
theme = "book"
enableGitInfo = false
relativeURLs = true

[params]
  # Hide the RHS in-doc table of contents
  # BookToC = false
  BookRepo = 'https://github.com/jamespfennell/texcraft'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/master/docs'
  BookSection = '*'
  BookSearch = false

[menu]

[[menu.after]]
  name = "Playground"
  url = "https://play.texcraft.dev"
  weight = 100

[[menu.after]]
  name = "GitHub"
  url = "https://github.com/jamespfennell/texcraft"
  weight = 120
