# baseURL = "http://texcraft.dev"
languageCode = "en-us"
title = "Texcraft"
theme = "book"
enableGitInfo = false
relativeURLs = true

[params]
  # Hide the RHS in-doc table of contents
  # BookToC = false
  BookRepo = 'https://github.com/jamespfennell/texcraft'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/master/docs'
  BookSection = '*'
  BookSearch = false

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Rust documentation"
  url = "/rustdoc/texcraft"
  weight = 10

[[menu.after]]
  parent = "Rust documentation"
  name = "Commands API"
  url = "/rustdoc/texcraft/tex/command"
  target = ""
  weight = 11

[[menu.after]]
  name = "GitHub repo"
  url = "https://github.com/jamespfennell/texcraft"
  weight = 20
