name: Texcraft CI jobs

on: [push, pull_request]

jobs:
  unit-and-doc-tests-ubuntu:
    uses: ./.github/workflows/unit-and-doc-tests.yml
    with:
      os: ubuntu-latest

  unit-and-doc-tests-macos:
    uses: ./.github/workflows/unit-and-doc-tests.yml
    with:
      os: macOS-latest

  unit-and-doc-tests-windows:
    uses: ./.github/workflows/unit-and-doc-tests.yml
    with:
      os: windows-latest

  compile-dev-targets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.94.0

      - name: Compile the benchmarks
        run: cargo bench --no-run

      - name: Compile the fuzz targets
        run: cargo build --bin fuzz_tftopl

  style-enforcement:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.94.0
          components: clippy
      - run: cargo clippy --all-features -- -D warnings

  playground_texcraft_dev:
    needs: unit-and-doc-tests-ubuntu
    uses: ./.github/workflows/playground.texcraft.dev.yml
    with:
      push_to_registry: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    secrets: inherit

  hyphenate_dev:
    needs: unit-and-doc-tests-ubuntu
    uses: ./.github/workflows/hyphenate.dev.yml
    with:
      push_to_registry: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    secrets: inherit

  docs_texcraft_dev:
    needs: unit-and-doc-tests-ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: jamespfennell
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          tags: jamespfennell/texcraft.dev:latest
          file: ./docs/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
