name: Texcraft CI jobs

on: [push, pull_request]


jobs:
  unit-and-doc-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run the tests
        uses: actions-rs/cargo@v1
        with:
          command: test

  benchmarks:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run the benchmarks
        uses: actions-rs/cargo@v1
        with:
          command: bench

  style-enforcement:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings

  build-the-website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: jamespfennell
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: jamespfennell/texcraft.dev:latest
          file: ./docs/Dockerfile
          # Only push to Docker Hub if this workflow is a push to main
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

  build-the-playground:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: jamespfennell
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: jamespfennell/play.texcraft.dev:latest
          file: ./playground/Dockerfile
          # Only push to Docker Hub if this workflow is a push to main
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
