name: hyphenate.dev

on: [push, pull_request]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f sites/hyphenate.dev/Dockerfile -t hyphenate.dev .

      - name: Start server
        run: docker run -d -p 8765:80 hyphenate.dev

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install test dependencies
        run: npm install
        working-directory: sites/hyphenate.dev

      - name: Run smoke test
        run: npm test
        working-directory: sites/hyphenate.dev

  build-and-push:
    runs-on: ubuntu-latest
    needs: e2e-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: jamespfennell
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: sites/hyphenate.dev/Dockerfile
          push: true
          tags: jamespfennell/hyphenate.dev:latest
