name: Unit and doc tests

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true

jobs:
  unit-and-doc-tests:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.94.0

      - name: Run the tests
        run: cargo test

      - name: Build the binaries
        run: cargo build --bin randtex --bin texcraft --bin pltotf --bin tftopl --bin tfmtools
